name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        include:
          - name: linux-amd64
            target: bun-linux-x64
            outfile: harmonic-linux-amd64
          - name: linux-arm64
            target: bun-linux-arm64
            outfile: harmonic-linux-arm64
          - name: macos-arm64
            target: bun-darwin-arm64
            outfile: harmonic-macos-arm64
          - name: macos-amd64
            target: bun-darwin-x64
            outfile: harmonic-macos-amd64
          - name: windows-amd64
            target: bun-windows-x64
            outfile: harmonic-windows-amd64.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install packages
        run: bun install

      - name: Build ${{ matrix.name }}
        run: |
          mkdir -p dist
          bun run build --target=${{ matrix.target }} --outfile dist/${{ matrix.outfile }}

      - name: Upload binary (${ { matrix.name }})
        uses: actions/upload-artifact@v4
        with:
          name: harmonic-${{ matrix.name }}
          path: dist/${{ matrix.outfile }}
